### PR TITLE
swflite spritesheet generation & png compression

### PR DESCRIPTION
**Pull request by onMouseUp**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[lime/project/ProjectXMLParser.hx, line 695 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSOK1Q2VMExQOOEexT:-LCSOK1R8PhFWattKQLU:b-4ah0ez) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/project/ProjectXMLParser.hx#L695)):*
> ```Haxe
> 		var fileName:String = "swfSpritesheet"; // default value if fileName is not set
> 		var targetDir:String = "";
> 		var pathToClassicFramework:String = PathHelper.getHaxelib(new Haxelib("duell_classic-framework"));
> ```

Not a big fan of having a dependency on the duell_classic-framework here.
* Not all games use the classic-framework ( robotlegs for example )
* Lime should be usable outside of GD context

Why not store a default packConfig + libs in lime?

---

*[lime/project/ProjectXMLParser.hx, line 705 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSOl-s5T1EK8L96fyj:-LCSOl-s5T1EK8L96fyk:b-g1tr91) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/project/ProjectXMLParser.hx#L705)):*
> ```Haxe
> 			fileName = element.att.fileName;
> 		} else {
> 			LogHelper.info("[SwfSpritesheet] --> You didn't specify the attribute 'fileName' of element <swfSpritesheet/> --> default name: " + "'" + fileName + "'" + " will be used");
> ```

no need to change, but FYI, if you use single quotes for the string, you can use variable substitution: 
`'default name: "${fileName}" will be used'`

---

*[lime/project/ProjectXMLParser.hx, line 776 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSTp0c5NxP0iHB-kZW:-LCSTp0c5NxP0iHB-kZX:b-jwcnh) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/project/ProjectXMLParser.hx#L776)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> if (FileSystem.exists(pathToCacheFile)) {
> 			var value = File.getContent(pathToCacheFile);
> 			atlasBuildCache = Json.parse(value);
> 		} else {
> 			atlasBuildCache = {metaFilePath:"", textureFilePath:"", enabled:true};
>		}
> ```
</details>

Duplicate code from `SwfspritesheetHelper::readCacheFile()` could be factorized

---

*[lime/tools/helpers/PngCompressionHelper.hx, line 23 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSReg--v8s-CyGgpmr:-LCSReg--v8s-CyGgpms:b-w2i2ym) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/PngCompressionHelper.hx#L23)):*
> ```Haxe
> 		baseDir = Sys.getCwd();
> 
> 		checkIfImagePathesValid(exportBaseDir);
> ```

Typo, checkIfImagePathsValid()

---

*[lime/tools/helpers/PngCompressionHelper.hx, line 55 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSS7gc8U8CbG-dQGQ8:-LCSS7gc8U8CbG-dQGQ9:bkeqjl4) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/PngCompressionHelper.hx#L55)):*
> ```Haxe
> 	{
> 		var fileName:String = getPlatformFileName();
> 		var toolsPath:String = PathHelper.combine(pngCompression.toolsDir, "pngquant-mac");
> ```

Use `getPlatformFileName()` for the program name 

Also take a look at webpack in lime. They have binaries for linux too. Check how they use it, and then add the linux packages from pngquant so that we can use this feature out of the box on linux too :)

---

*[lime/tools/helpers/SwfSpritesheetHelper.hx, line 102 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSUSzd-MIEpDKnZdoS:-LCSUSzd-MIEpDKnZdoT:b-g4xyge) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/SwfSpritesheetHelper.hx#L102)):*
> ```Haxe
> 	}
> 
> 	private static function copyPackFileToTempDirectory():Void {
> ```

What's the goal of copying the pack.json file to the temp directory? Why not use it directly from the packConfigDir?

---

*[lime/tools/helpers/SwfSpritesheetHelper.hx, line 111 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSUr38CIrY8GfZSidD:-LCSUr38CIrY8GfZSidE:b8bk2qz) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/SwfSpritesheetHelper.hx#L111)):*
> ```Haxe
> 			FileHelper.copyFile(sourcePackFile, targetPackFile);
> 		} else {
> 			LogHelper.error("[SwfSpritesheet] could not find pack.json: --> " + sourcePackFile);
> ```

you should probably throw here because the next code will causes exceptions ( see `parsePackJson` )

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)*

**Comment by rams3s** [comment]
Reviewed 5 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)*

**Comment by rams3s** [comment]
Reviewed 3 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)*

**Comment by onMouseUp** [comment]
Review status: 1 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 695 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSOK1Q2VMExQOOEexT:-LCdgBb69SXE5EoAJHIU:b-8b92d8) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/project/ProjectXMLParser.hx#L695)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Not a big fan of having a dependency on the duell_classic-framework here.
* Not all games use the classic-framework ( robotlegs for example )
* Lime should be usable outside of GD context

Why not store a default packConfig + libs in lime?
</blockquote></details>

moved pack config into lime-lib

---

*[lime/project/ProjectXMLParser.hx, line 705 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSOl-s5T1EK8L96fyj:-LCdgUZfD5OmcCzKKS35:bd5wh7g) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/project/ProjectXMLParser.hx#L705)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

no need to change, but FYI, if you use single quotes for the string, you can use variable substitution: 
`'default name: "${fileName}" will be used'`
</blockquote></details>

good hint!

---

*[lime/project/ProjectXMLParser.hx, line 776 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSTp0c5NxP0iHB-kZW:-LCdgZKu4kHBIlWjpUr9:b-6e6akr) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/project/ProjectXMLParser.hx#L776)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> ```
> if (FileSystem.exists(pathToCacheFile)) {
> 			var value = File.getContent(pathToCacheFile);
> 			atlasBuildCache = Json.parse(value);
> 		} else {
> 			atlasBuildCache = {metaFilePath:"", textureFilePath:"", enabled:true};
>		}
> ```
Duplicate code from `SwfspritesheetHelper::readCacheFile()` could be factorized
</blockquote></details>

provided a public method in SwfspritesheetHelper, will be used from ProjectXMLParser

---

*[lime/tools/helpers/PngCompressionHelper.hx, line 23 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSReg--v8s-CyGgpmr:-LCdgpDKCtzNxjyNNwXl:b-7ql1td) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/PngCompressionHelper.hx#L23)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Typo, checkIfImagePathsValid()
</blockquote></details>

fixed

---

*[lime/tools/helpers/PngCompressionHelper.hx, line 55 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSS7gc8U8CbG-dQGQ8:-LCdgqkK2sWZuQS3nbRS:bkqijkm) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/PngCompressionHelper.hx#L55)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Use `getPlatformFileName()` for the program name 

Also take a look at webpack in lime. They have binaries for linux too. Check how they use it, and then add the linux packages from pngquant so that we can use this feature out of the box on linux too :)
</blockquote></details>

fixed, now  fileName from getPlatformFileName() will be used.
pngquant for Linux still unsolved...

---

*[lime/tools/helpers/SwfSpritesheetHelper.hx, line 102 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSUSzd-MIEpDKnZdoS:-LCdhEfHCh2jYC1S5TOq:bm9etyo) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/SwfSpritesheetHelper.hx#L102)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

What's the goal of copying the pack.json file to the temp directory? Why not use it directly from the packConfigDir?
</blockquote></details>

no option to target pack config in command line. Has to be located inside the source-folder of pngs 

---

*[lime/tools/helpers/SwfSpritesheetHelper.hx, line 111 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSUr38CIrY8GfZSidD:-LCdheHAAo_7xw73DW_N:b-ithf5l) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/SwfSpritesheetHelper.hx#L111)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

you should probably throw here because the next code will causes exceptions ( see `parsePackJson` )
</blockquote></details>

LogHelper.error(...) will stop build process immediately

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)*

**Comment by NuclearCookie** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lime/tools/helpers/PngCompressionHelper.hx, line 55 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSS7gc8U8CbG-dQGQ8:-LCh7NtGBpWs9by_ieO1:b-o17n4v) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/PngCompressionHelper.hx#L55)):*
<details><summary><i>Previously, onMouseUp (onMouseUp) wrote…</i></summary><blockquote>

fixed, now  fileName from getPlatformFileName() will be used.
pngquant for Linux still unsolved...
</blockquote></details>

OK for linux part. This program is available on most package managers. Thanks.

---

*[lime/tools/helpers/SwfSpritesheetHelper.hx, line 102 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSUSzd-MIEpDKnZdoS:-LCh7avG6jLzTSLCWoNX:b32w0x) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/SwfSpritesheetHelper.hx#L102)):*
<details><summary><i>Previously, onMouseUp (onMouseUp) wrote…</i></summary><blockquote>

no option to target pack config in command line. Has to be located inside the source-folder of pngs 
</blockquote></details>

OK

---

*[lime/tools/helpers/SwfSpritesheetHelper.hx, line 111 at r1](https://reviewable.io/reviews/fishingcactus/lime/42#-LCSUr38CIrY8GfZSidD:-LCh7iP-EJRtTlZPW4uP:b32w0x) ([raw file](https://github.com/fishingcactus/lime/blob/d47215c6e0d87f870e8c9706402e5f6b300f79e8/lime/tools/helpers/SwfSpritesheetHelper.hx#L111)):*
<details><summary><i>Previously, onMouseUp (onMouseUp) wrote…</i></summary><blockquote>

LogHelper.error(...) will stop build process immediately
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)*

**Comment by rams3s** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/42)*

**Pull request merged**
