### PR TITLE
Added jquery and jqueryui for the dev Tools

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/25)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/25#-:-KkGHHoSAIJs_r0ZFfM0:bnfp4nl)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[lime/_backend/html5/HTML5Application.hx, line 71 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/25#-KkGJ0b98iIJ_HSd75Y9:-KkGJ0b98iIJ_HSd75YA:b6h9aw9) ([raw file](https://github.com/fishingcactus/lime/blob/00d07466e7e578a58cec09a4668435f9a066ca59/lime/_backend/html5/HTML5Application.hx#L71)):*
> ```Haxe
> 				document.getElementsByTagName('head')[0].appendChild(script);
> 
> 				var head  = document.getElementsByTagName('head')[0];
> ```

you query this 3 times, why not put it at the top and use it afterward?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/25)*

**Comment by gogoprog** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/_backend/html5/HTML5Application.hx, line 71 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/25#-KkGJ0b98iIJ_HSd75Y9:-KkGP8C73ZywRxSEqnjp:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/00d07466e7e578a58cec09a4668435f9a066ca59/lime/_backend/html5/HTML5Application.hx#L71)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

you query this 3 times, why not put it at the top and use it afterward?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/25)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/25)*

**Pull request merged**
