### PR TITLE
Added option to embed spector

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/39)

### CODE REVIEW

**Comment by gogoprog** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/_backend/html5/HTML5Window.hx, line 242 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/39#-KyPevL7nIZ3kANq9nDE:-KyPevL7nIZ3kANq9nDF:bd65o06) ([raw file](https://github.com/fishingcactus/lime/blob/f45ffaa8f4f5b0c2e15e962cedb299b6ed4410b9/lime/_backend/html5/HTML5Window.hx#L242)):*
> #if spector
> 			untyped __js__("
> 				var spector = new SPECTOR.Spector();
> 				spector.displayUI();
> 				");
> 		#end
What kind of UI is it? Isn't it for dev/debug only?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/39)*

**Comment by rams3s** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/_backend/html5/HTML5Window.hx, line 242 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/39#-KyPevL7nIZ3kANq9nDE:-KyPxE4uU5WRqhVZfJ8H:be2xv1d) ([raw file](https://github.com/fishingcactus/lime/blob/f45ffaa8f4f5b0c2e15e962cedb299b6ed4410b9/lime/_backend/html5/HTML5Window.hx#L242)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

> #if spector
> 			untyped __js__("
> 				var spector = new SPECTOR.Spector();
> 				spector.displayUI();
> 				");
> 		#end
What kind of UI is it? Isn't it for dev/debug only?
</blockquote></details>

yep... that's the UI to capture GL calls.
I chose to embed it (vs relying on the extension) so that we can use the version modified by Pieter which requires promises (that don't work in the extension right now).

We can do something like that if that's what you meant:
```
#if (dev && spector)
...
#end
```
or even
```
#if dev
if (SPECTOR)
{
    ...
}
#end
```

Any preference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/39)*

**Comment by gogoprog** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/_backend/html5/HTML5Window.hx, line 242 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/39#-KyPevL7nIZ3kANq9nDE:-KyQ0yH7TuiTF1l5m07W:b-bw17rx) ([raw file](https://github.com/fishingcactus/lime/blob/f45ffaa8f4f5b0c2e15e962cedb299b6ed4410b9/lime/_backend/html5/HTML5Window.hx#L242)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

yep... that's the UI to capture GL calls.
I chose to embed it (vs relying on the extension) so that we can use the version modified by Pieter which requires promises (that don't work in the extension right now).

We can do something like that if that's what you meant:
```
#if (dev && spector)
...
#end
```
or even
```
#if dev
if (SPECTOR)
{
    ...
}
#end
```

Any preference?
</blockquote></details>

But atm now 'if dev' is missing right?

I prefer the first one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/39)*

**Comment by rams3s** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/_backend/html5/HTML5Window.hx, line 242 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/39#-KyPevL7nIZ3kANq9nDE:-KyQ8gR8IbAj93OADnm7:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/f45ffaa8f4f5b0c2e15e962cedb299b6ed4410b9/lime/_backend/html5/HTML5Window.hx#L242)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

But atm now 'if dev' is missing right?

I prefer the first one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/39)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/39#-:-KyR143MlcOHg0L1ztoZ:bnfp4nl)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/39#-:-KyR25rwuRyjcBbRvKzV:bnfp4nl)*

**Pull request merged**
