### PR TITLE
better generated code

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/9)

### CODE REVIEW

**Comment by gogoprog** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/graphics/format/BMP.hx, line 93 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/9#-KcU3r9Gf21C3-J_fm8F:-KcU3r9Gf21C3-J_fm8G:b-cn693v) ([raw file](https://github.com/fishingcactus/lime/blob/4c2b6a09c5471cf3b1c0ed0705a372ab102fb663/lime/graphics/format/BMP.hx#L93)):*
> ```Haxe
> 			var i = 0;
> 			while (i < 48) {
> 				++i;
> ```

What does it change in the generated code to do that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/9)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/graphics/format/BMP.hx, line 93 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/9#-KcU3r9Gf21C3-J_fm8F:-KcU4LlQTZ9SkSNPGtZM:b-59moyz) ([raw file](https://github.com/fishingcactus/lime/blob/4c2b6a09c5471cf3b1c0ed0705a372ab102fb663/lime/graphics/format/BMP.hx#L93)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

What does it change in the generated code to do that?
</blockquote></details>

Compiled code for a for loop where the iterator is not used compiles to something like this:
```
var g1 = 0;
var g2 = 48;
while( g1 < g2 ) {
var i = g1++;
...
}
```
giving an unused variable i inside each of those ifs.

Changing to this format  keeps the code almost like it is written

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/9)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/9#-:-KcU9DR0JXPB_TnBd8zf:bnfp4nl)*

**Comment by NuclearCookie** [comment]
@crazyjul  Simplified this MR. review with `?w=1` to ignore all whitespace changes

**Comment by gogoprog** [comment]
Reviewed 2 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/9)*

**Comment by gogoprog** [comment]
Not merge-able atm

**Comment by NuclearCookie** [comment]
Updated @gogoprog

**Comment by crazyjul** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/9)*

**Comment by gogoprog** [comment]
Reviewed 1 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/9)*

**Pull request merged**
