### PR TITLE
Feature/support sound parameters

### PR DESCRIPTION
**Pull request by Ihsene**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/36)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lime/Assets.hx, line 342 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgSP7rRp4_Mk1XSNH1:-KvgSP7rRp4_Mk1XSNH2:bxbwrk7) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/Assets.hx#L342)):*
> ```Haxe
> 	}
> 
> 	public static function getSoundData(id:String):AudioParameters {
> ```

No longer needed? ( I see 3 implementations of this function.)

---

*[lime/Assets.hx, line 978 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgRjoa-2ujo1NAZIaR:-KvgRjoa-2ujo1NAZIaS:b-cm9yac) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/Assets.hx#L978)):*
> public function getSoundData(id:String):AudioParameters {
>  
> 		return null;
> 	}
No longer needed

---

*[lime/audio/AudioParameters.hx, line 3 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgRHU6881yo2QSkZz1:-KvgRHU7O1XuJYoMdp18:bect0yt) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/audio/AudioParameters.hx#L3)):*
> ```Haxe
> package lime.audio;
> 
> class AudioParameters {
> ```

AudioParameters is a confusing name because it might refer to the length, bitrate, ....
I propse to change it to:
`ExtraSoundOptions` or something like that

---

*[lime/project/ProjectXMLParser.hx, line 641 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgRnHPcMnhydgPLaJx:-KvgRnHPcMnhydgPLaJy:b6c75iw) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/project/ProjectXMLParser.hx#L641)):*
> ```Haxe
> 					asset.id = id;
> 					
> 					if(childElement.has.start && childElement.has.duration)
> ```

Only allow this for sound or music properties. ( check the `childElement.name` )

---

*[templates/haxe/DefaultAssetLibrary.hx, line 72 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgS3JryLCtJlPppDIi:-KvgS3JryLCtJlPppDIj:b-exvug3) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/templates/haxe/DefaultAssetLibrary.hx#L72)):*
> ```Haxe
> 
> 		::if (assets != null)::
> 		::foreach assets::::if (type == "sound")::
> ```

sound or music. Music will be set automatically for larger files, correct me if I'm wrong

---

*[templates/haxe/DefaultAssetLibrary.hx, line 394 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgSC99-x87s8tSXxRx:-KvgSC99-x87s8tSXxRy:b-oke2n5) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/templates/haxe/DefaultAssetLibrary.hx#L394)):*
> ```Haxe
> 	}
> 
> 	public override function getSoundData(id:String):AudioParameters {
> ```

no overrid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
We have getSoundData in the class AssetLibrary and in DefaultAssetLibrary. DefaultAssetLibrary extends AssetLibrary and override the getSoundData function. Finally, we have getSoundData in the class lime.Assets.

**Comment by Ihsene** [comment]
it's right for the music or sound. If a file is too big, it become a music

**Comment by Ihsene** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[lime/Assets.hx, line 342 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgSP7rRp4_Mk1XSNH1:-KvgXSDdBvPQw4U7GIiX:bg4rj4b) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/Assets.hx#L342)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

No longer needed? ( I see 3 implementations of this function.)
</blockquote></details>

In fact, we need the 3 implementation, the first one is for retrieve the data from the Map and the two other, one in Assets that return null and the other in DefaultAssetLibrary (extends Assets) that get the data from the map, the Map instance is in DefaultAssertLibrary, so we can not access it in Assets. This is why, it's done like this. I follow the same way as getPath function.

---

*[lime/Assets.hx, line 978 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgRjoa-2ujo1NAZIaR:-KvgZHPITl14Oqi_nJLT:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/Assets.hx#L978)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> public function getSoundData(id:String):AudioParameters {
>  
> 		return null;
> 	}
No longer needed
</blockquote></details>

Done.

---

*[lime/audio/AudioParameters.hx, line 3 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgRHU6881yo2QSkZz1:-KvgZId2_1tiLDKiNrs-:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/audio/AudioParameters.hx#L3)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

AudioParameters is a confusing name because it might refer to the length, bitrate, ....
I propse to change it to:
`ExtraSoundOptions` or something like that

</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 72 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgS3JryLCtJlPppDIi:-KvgYv0J4XMmUxiy8wmc:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/templates/haxe/DefaultAssetLibrary.hx#L72)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

sound or music. Music will be set automatically for larger files, correct me if I'm wrong
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 394 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgSC99-x87s8tSXxRx:-KvgYtgREAMA1tWEQXBm:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/templates/haxe/DefaultAssetLibrary.hx#L394)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

no overrid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 641 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvgRnHPcMnhydgPLaJx:-Kvgj3P3xykHD6K0ud8x:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/c26e35e5f19127b08a7ef838a102dfccc6ff85bc/lime/project/ProjectXMLParser.hx#L641)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Only allow this for sound or music properties. ( check the `childElement.name` )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 641 at r2](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvlZV9vxPDTpSqCFrjE:-KvlZV9vxPDTpSqCFrjF:bz1hstj) ([raw file](https://github.com/fishingcactus/lime/blob/cc8cfe3fa78048283f0370709e6eb9e1f1a312c5/lime/project/ProjectXMLParser.hx#L641)):*
> ```Haxe
> 					asset.id = id;
> 					
> 					if(childElement.has.name && 
> ```

`.has.name` checks for the `.att.name`, not for `.name`.
xml nodes NEED to have `.name`. for example in `<sound/>`, the `.name` is `"sound"`.
The `.att.name` refers to `<sound name="test"/>`

So, no need to check `childElement.has.name`

---

*[templates/haxe/DefaultAssetLibrary.hx, line 77 at r2](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvlZwUT0HEeQ4ojA-Ri:-KvlZwUT0HEeQ4ojA-Rj:bw11719) ([raw file](https://github.com/fishingcactus/lime/blob/cc8cfe3fa78048283f0370709e6eb9e1f1a312c5/templates/haxe/DefaultAssetLibrary.hx#L77)):*
> ```Haxe
> 					extraSoundOptions.set( '::sourcePath::', new ExtraSoundOptions(::data.start::, ::data.duration::));
> 				::else::
> 					::if (type == "music")::
> ```

merge into `::elseif::`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 641 at r2](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvlZV9vxPDTpSqCFrjE:-KvlbD0Zin7PcEet-xiQ:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/cc8cfe3fa78048283f0370709e6eb9e1f1a312c5/lime/project/ProjectXMLParser.hx#L641)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

`.has.name` checks for the `.att.name`, not for `.name`.
xml nodes NEED to have `.name`. for example in `<sound/>`, the `.name` is `"sound"`.
The `.att.name` refers to `<sound name="test"/>`

So, no need to check `childElement.has.name`
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 77 at r2](https://reviewable.io:443/reviews/fishingcactus/lime/36#-KvlZwUT0HEeQ4ojA-Ri:-KvlbFOBspU25ZDWT-4i:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/cc8cfe3fa78048283f0370709e6eb9e1f1a312c5/templates/haxe/DefaultAssetLibrary.hx#L77)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

merge into `::elseif::`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36#-:-KvlbnD7YUMivZ0mqa27:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 588 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UADHAyV8Lr45T7Pu:-Kw-UADHAyV8Lr45T7Pv:biz2h8c) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L588)):*
> ```Haxe
> 		if (path == "" && (element.has.include || element.has.exclude || type != null )) {
> 			
> 			LogHelper.error ("In order to use 'include' or 'exclude' on <asset /> nodes, you must specify also specify a 'path' attribute");
> ```

typo. only 1 specify needed

---

*[lime/project/ProjectXMLParser.hx, line 642 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UHyUz3BNie-p4xFa:-Kw-UHyUz3BNie-p4xFb:bd5d6lg) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L642)):*
> ```Haxe
> 						include = substitute (element.att.include);
> 					} else {
> 							include = "*";
> ```

indentation

---

*[templates/haxe/DefaultAssetLibrary.hx, line 72 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UN5mlqHE1dsnj1Bf:-Kw-UN5mlqHE1dsnj1Bg:bdzw6v1) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L72)):*
> ```Haxe
> 		::if (assets != null)::
> 			::foreach assets::
> 				::if (data.duration != null)::
> ```

check both start and duration

---

*[templates/haxe/DefaultAssetLibrary.hx, line 100 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UdJauwpZZmZJVAjp:-Kw-UdJauwpZZmZJVAjq:b2kvi1n) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L100)):*
> ::if (type == "sound")::
> 					id = '::sourcePath::';
> 				::elseif (type == "music")::
> 					id = '::sourcePath::';
> 				::end::
why is this necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by gogoprog** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 414 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw08Um_ol81rGa6Z4nz:-Kw08Um_ol81rGa6Z4o-:bru1ggo) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L414)):*
> public override function getExtraSoundOptions(id:String):ExtraSoundOptions {
> 		return extraSoundOptions.get(id);
> 	}

surround with #if html5

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 588 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UADHAyV8Lr45T7Pu:-Kw082GMSBhRwqscSOrl:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L588)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

typo. only 1 specify needed
</blockquote></details>

Done.

---

*[lime/project/ProjectXMLParser.hx, line 642 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UHyUz3BNie-p4xFa:-Kw06GGQhOP0bNhXpyXn:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L642)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 72 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UN5mlqHE1dsnj1Bf:-Kw06H0mv-Ga0FsBLG6b:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L72)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

check both start and duration
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 100 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UdJauwpZZmZJVAjp:-Kw06IW3kNStVpr-ZfQh:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L100)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> ::if (type == "sound")::
> 					id = '::sourcePath::';
> 				::elseif (type == "music")::
> 					id = '::sourcePath::';
> 				::end::
why is this necessary?
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 414 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw08Um_ol81rGa6Z4nz:-Kw08wcSHfkpYUwT_lrF:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L414)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

> public override function getExtraSoundOptions(id:String):ExtraSoundOptions {
> 		return extraSoundOptions.get(id);
> 	}

surround with #if html5
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 560 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw0CG_JvuJ1qOeex2Sl:-Kw0CG_JvuJ1qOeex2Sm:b-4aw9l5) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L560)):*
> ```Haxe
> 					
> 					var asset = new Asset (path + childPath, targetPath + childTargetPath, childType, childEmbed);
> 					asset.id = id;
> ```

Why remove asset.id ?

---

*[lime/project/ProjectXMLParser.hx, line 642 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UHyUz3BNie-p4xFa:-Kw0CKNSXx8-ocoqZ2hb:b-koqj7d) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L642)):*
<details><summary><i>Previously, Ihsene wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, the `include = "*";` is one tab too much to the right.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 72 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UN5mlqHE1dsnj1Bf:-Kw0CRdONJXmA-Xnban_:b-9wxm8n) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L72)):*
<details><summary><i>Previously, Ihsene wrote…</i></summary><blockquote>

Done.
</blockquote></details>

didn't work with && ?

---

*[templates/haxe/DefaultAssetLibrary.hx, line 75 at r5](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw0CZn37FY_38wVwSxA:-Kw0CZn37FY_38wVwSxB:b3l71p3) ([raw file](https://github.com/fishingcactus/lime/blob/041bb8bb411759f40f8e83255a37fa5d687f54bb/templates/haxe/DefaultAssetLibrary.hx#L75)):*
> ```Haxe
> 					::if (data.start != null)::
> 						::if (type == "sound")::
> 							extraSoundOptions.set( '::resourceName::', new ExtraSoundOptions(::data.start::, ::data.duration::));
> ```

Where is this coming from now? :upside_down_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 560 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw0CG_JvuJ1qOeex2Sl:-Kw0SqdUqDlTk3pH8pcE:b-o0d7zt) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L560)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Why remove asset.id ?
</blockquote></details>

issue with the id attribut, i modified the code and restore the line

---

*[lime/project/ProjectXMLParser.hx, line 642 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UHyUz3BNie-p4xFa:-Kw0T3utL3TeL5xhz9c1:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L642)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

no, the `include = "*";` is one tab too much to the right.
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 75 at r5](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw0CZn37FY_38wVwSxA:-Kw0HIjJZk429ZCP-ajC:basrxog) ([raw file](https://github.com/fishingcactus/lime/blob/041bb8bb411759f40f8e83255a37fa5d687f54bb/templates/haxe/DefaultAssetLibrary.hx#L75)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Where is this coming from now? :upside_down_face: 
</blockquote></details>

Resolved in discussion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[lime/project/ProjectXMLParser.hx, line 560 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw0CG_JvuJ1qOeex2Sl:-Kw45LkE-K_-DhqEcPnq:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L560)):*
<details><summary><i>Previously, Ihsene wrote…</i></summary><blockquote>

issue with the id attribut, i modified the code and restore the line
</blockquote></details>

Done.

---

*[lime/project/ProjectXMLParser.hx, line 642 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UHyUz3BNie-p4xFa:-Kw45PO3WMdz_GvvgUOH:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/lime/project/ProjectXMLParser.hx#L642)):*
<details><summary><i>Previously, Ihsene wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 72 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw-UN5mlqHE1dsnj1Bf:-Kw45Qx4dXshKBo0jO52:b-m64smi) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L72)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

didn't work with && ?
</blockquote></details>

I try but  can not make it work, same issue with type == "sound" && type =="music"

---

*[templates/haxe/DefaultAssetLibrary.hx, line 414 at r4](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw08Um_ol81rGa6Z4nz:-Kw45HbR6JmvfgdJbrGA:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/6a2bc4c3af2db2bc33738423d188d7810dd79028/templates/haxe/DefaultAssetLibrary.hx#L414)):*
<details><summary><i>Previously, Ihsene wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[templates/haxe/DefaultAssetLibrary.hx, line 75 at r5](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw0CZn37FY_38wVwSxA:-Kw45gn2qEbTNb3VfnO9:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/041bb8bb411759f40f8e83255a37fa5d687f54bb/templates/haxe/DefaultAssetLibrary.hx#L75)):*
<details><summary><i>Previously, Ihsene wrote…</i></summary><blockquote>

Resolved in discussion
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36#-:-Kw4FmBRx-mPP0R5jCWM:bnfp4nl)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[lime/audio/ExtraSoundOptions.hx, line 7 at r6](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw5-AuClVuPC0AUem2G:-Kw5-AuClVuPC0AUem2H:bpx9x7n) ([raw file](https://github.com/fishingcactus/lime/blob/b4d3680d8c0099eed4e67ed3c6a33afc382e8e79/lime/audio/ExtraSoundOptions.hx#L7)):*
> ```Haxe
>     public var duration:Int;
> 
>     public function new(start:Int = 0, duration:Int) {
> ```

Default value doesn't seem to be useful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by Ihsene** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/audio/ExtraSoundOptions.hx, line 7 at r6](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kw5-AuClVuPC0AUem2G:-Kw5717fWkCDcftaI-Zn:b-zc5bix) ([raw file](https://github.com/fishingcactus/lime/blob/b4d3680d8c0099eed4e67ed3c6a33afc382e8e79/lime/audio/ExtraSoundOptions.hx#L7)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Default value doesn't seem to be useful
</blockquote></details>

i put it a first to let the the possibility to only modify the duration but the issue with the gap comes from the start time so endeed it's not necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by gogoprog** [comment]
Reviewed 1 of 5 files at r2, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
There's a bug in this code. When doing this:
```
	<assets path="Assets/sounds">
		<sound include="*.m4a"/>
		<sound name="foo.m4a" start="150" duration="2800"/>
		<sound name="bar.m4a" preload="5"/>
	</assets>
```

The foo and bar sound will be added twice in the list of assets. Then it depends on the order of execution to see if we will use the one with or without sound options.
Solution: `assets` should be a map.

Behavior:
1) don't allow duplicates. Use first definition and stick with that
2) override existing assets

I prefer option 2

**Comment by rams3s** [comment]
Reviewed 1 of 5 files at r2, 1 of 3 files at r6, 2 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lime/Assets.hx, line 384 at r9](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kx8kDrCUpMxYuL7p45j:-Kx8kDrCUpMxYuL7p45k:b-gcms8t) ([raw file](https://github.com/fishingcactus/lime/blob/2643b406e539edb19703a7fcd33364bd1fed003f/lime/Assets.hx#L384)):*
> return "";
> 			
> 		}
> 		return "";

should just let the trailing return null do its job ;)

---

*[lime/project/ProjectXMLParser.hx, line 469 at r9](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kx8kmBG06mP_Jgsmdr_:-Kx8kmBG06mP_Jgsmdra:b-ini4xh) ([raw file](https://github.com/fishingcactus/lime/blob/2643b406e539edb19703a7fcd33364bd1fed003f/lime/project/ProjectXMLParser.hx#L469)):*
> ```Haxe
> 		var excludeChildElement = ".*|cvs|thumbs.db|desktop.ini|*.fla|*.hash";
> 		var includeChildElement = "";
> 		if (element.elements.hasNext ()) {
> ```

considering the for loop coming right after, is this test necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by NuclearCookie** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[lime/Assets.hx, line 384 at r9](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kx8kDrCUpMxYuL7p45j:-KxCHo-R6y7sNiu_x-KG:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/2643b406e539edb19703a7fcd33364bd1fed003f/lime/Assets.hx#L384)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> return "";
> 			
> 		}
> 		return "";

should just let the trailing return null do its job ;)
</blockquote></details>

Done.

---

*[lime/project/ProjectXMLParser.hx, line 469 at r9](https://reviewable.io:443/reviews/fishingcactus/lime/36#-Kx8kmBG06mP_Jgsmdr_:-KxCHqEUF_-JMAjtlnEg:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/2643b406e539edb19703a7fcd33364bd1fed003f/lime/project/ProjectXMLParser.hx#L469)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

considering the for loop coming right after, is this test necessary?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/36#-:-KxCV9Q2D5IrkD8fAmOZ:bnfp4nl)*

**Pull request merged**
