### PR TITLE
use fontforge instead of webify

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/4)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Needs fontforge binaries for windows and mac ( and linux32 )

**Comment by NuclearCookie** [comment]
and lib files for linux

**Comment by crazyjul** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/4)_

**Comment by crazyjul** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[lime/tools/helpers/HTML5Helper.hx, line 63 [r3]](https://reviewable.io:443/reviews/fishingcactus/lime/4#-KR3FjREoZe3693UGdLw:-KR3FjRF_n7voisvNna5:b-za3zta) ([raw file](https://github.com/fishingcactus/lime/blob/a88665bda99b1bc16b86473088a43b16e6e2fda0/lime/tools/helpers/HTML5Helper.hx#L63)):_

> ``` Haxe
>           if (LogHelper.verbose) {
> 
>               ProcessHelper.runCommand ("", fontforge, [ generate_script, input, output_base + ".eot", output_base + ".woff", output_base + ".svg" ], true, true, true);
> ```

the 3 true are inversed with webify regardin LogHelper.Verbose condition

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/4)_

**Comment by NuclearCookie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[lime/tools/helpers/HTML5Helper.hx, line 63 [r3]](https://reviewable.io:443/reviews/fishingcactus/lime/4#-KR3FjREoZe3693UGdLw:-KR3bLz1LF7krK96m4cf:b-896fix) ([raw file](https://github.com/fishingcactus/lime/blob/a88665bda99b1bc16b86473088a43b16e6e2fda0/lime/tools/helpers/HTML5Helper.hx#L63)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> the 3 true are inversed with webify regardin LogHelper.Verbose condition
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/4)_

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/4)_

**Comment by crazyjul** [comment]
Works on osx, need to test a windows build

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/4#-:-KR4NkbE4iJaLXBycT_M:bkf1sqx)_

**Pull request closed without merging**
