### PR TITLE
Feature/clean profile

### PR DESCRIPTION
**Pull request by gogoprog**
Clean Profile interface

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/lime/38)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/38#-:-KxgNdfrqieWxvkt2HZ_:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/38)*

**Comment by rams3s** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[lime/utils/ProfileTool.hx, line 5 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/38#-KxhIoJDsG0N6G52LQ68:-KxhIoJDsG0N6G52LQ69:ba0o0l8) ([raw file](https://github.com/fishingcactus/lime/blob/6edf0db32a196139088f0b1968b4541406f5260c/lime/utils/ProfileTool.hx#L5)):*
> ```Haxe
> #if profile
> 
> class ProfileTool
> ```

suggestion: what about adding Profile.help() to display the list of all profiling tools?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/38)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lime/utils/ProfileTool.hx, line 5 at r1](https://reviewable.io:443/reviews/fishingcactus/lime/38#-KxhIoJDsG0N6G52LQ68:-KxhJI07drcI0rAaAbKy:b-ul8jrf) ([raw file](https://github.com/fishingcactus/lime/blob/6edf0db32a196139088f0b1968b4541406f5260c/lime/utils/ProfileTool.hx#L5)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

suggestion: what about adding Profile.help() to display the list of all profiling tools?
</blockquote></details>

Good idea

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/38)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/38)*

**Comment by gogoprog** [comment]
Updated. Can you take a look?

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/lime/38#-:-L5Ezrt8Aw-1kSplTY2h:bnfp4nl)*

**Pull request merged**
